### PR TITLE
Issue #12 Adds a terms page

### PR DESCRIPTION
**Pull request by caprenter**
This may not be to your liking, and it commits us to using a
self hosted Matomo for web tracking.

So happy to rewrite/change alter, go all conventional etc

### CODE REVIEW

**Comment by caprenter** [comment]
Also just check how the links are set in the terms page to get back to the index page. Not sure if that's the best way - but it seems to work locally for me. I'm just clicking on index.html from my file system, not serviing it from a webserver.

**Comment by Plebster** [comment]
I used index.html#<resource> on the 404 page to redirect

**Comment by caprenter** [comment]
I'm running out of time today - I can fix later (but could be days) - happy for you to make consistent. The 404 page nav works fine for me so happy with your solution.

**Review by Plebster — CHANGES_REQUESTED** [review]
why are you change the link colours? this seems to be separate to the creating of the extra pages/ info and more a fundamental change of the theme that we're using...

this is an extension to the question I asked in another branch which I can't find now and the comment I made in #10 

can we have the css as a separate discussion/ issue

**Comment by caprenter** [comment]
The previous question about css, with a response is here: https://github.com/CooperativeIT/website/pull/21

Again, I'm relaxed about this. I made the change because the fix introduced a secondary problem (link colour/contrast) so I addressed it at the same time. 

Feel free to remove the css change and address it later if you like.

**Comment by Plebster** [comment]
I don't see a response to my css question... chasing my own tail it feels like

**Review by Plebster — COMMENTED** [review]
there is a reference to "I" and "We" in the text shouldn' these be changed with Cooperative IT?

**Pull request merged**
